services:
  mosquitto:
    image: eclipse-mosquitto:2.0.18
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      
  questdb:
    image: questdb/questdb:8.1.0
    restart: unless-stopped
    ports:
      - 9000:9000
      - 9009:9009
      - 8812:8812
      - 9003:9003

  consumer:
    build: 
      context: .
    depends_on:
      - mosquitto
      - questdb
    environment:
      MQTT_HOST: mosquitto
      MQTT_PORT: 1883
      QUESTDB_HOST: questdb
      QUESTDB_PORT: 9000

  web:
    build: 
      context: ./web
    depends_on:
      - questdb
    ports:
      - 9002:3000
    environment:
      QUESTDB_HOST: questdb
      QUESTDB_PORT: 9000