services:
  mosquitto:
    image: eclipse-mosquitto:2.0.18
    ports:
      - 1883:1883
      - 9001:9001
      
  questdb:
    image: questdb/questdb:8.1.0
    ports:
      - 9000:9000
      - 9009:9009
      - 8812:8812
      - 9003:9003

  consumer:
    build: 
      context: .
    environment:
      MQTT_HOST: mosquitto
      MQTT_PORT: 1883
      QUESTDB_HOST: db
      QUESTDB_PORT: 9000